version: '3.8'

services:
  signaling-server:
    image: node:18
    volumes:
      - ./signaling-server:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: sh -c "npm install && node server.js" 