name: trollface
description: A video calling app with face filters
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.25
  flutter_local_notifications: ^14.1.1
  timeago: ^3.4.0
  web_socket_channel: ^2.4.0
  uuid: ^3.0.7
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  flutter_webrtc: 0.9.47
  shared_preferences: ^2.2.0
  fl_chart: ^0.62.0
  path_provider: ^2.0.15
  csv: ^5.0.2
  just_audio: ^0.9.34

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/filters/
